# Generated by Django 4.2.4 on 2023-11-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('Description', models.TextField(blank=True)),
                ('Date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
